### ISSUE TITLE
How to build this project with vagrant?

### ISSUE THREAD

**Issue by lmnsyunhao** [ucla-pls/jbx#15]
Hi, Sorry for bothering you. I have a problem. I have already installed nixos18 in vagrant and `vagrant up && vagrant ssh`. 

But, when I run `./jbx analyse -a deadlocks.dirk -o baseline-transfer`, the log told me that 
```
trying file:///home/vagrant/jbx/proprietary/jdk-6u45-linux-x64.bin
curl: (37) Couldn't open file /home/vagrant/jbx/proprietary/jdk-6u45-linux-x64.bin
error: cannot download jdk-6u45-linux-x64.bin from any mirror
```
I have already copied and renamed `environment.nix.sample` to `environment.nix`, and the content of `environment.nix` is as following:
```
# Copy to environment.nix and fix to fit the required specs
{
  name = "Sample Computer";
  processor = "2.9 GHz Intel Core i5";
  cores = 2;
  memory = "1867 MHz DDR3";
  ppath = "file:///home/vagrant/jbx/proprietary/";
  memorysize = 8192;
}
```
I also put `jdk-6u45-linux-x64.bin` in the corresponding folder, like:
```
[vagrant@nixbox:~/jbx]$ ll /home/vagrant/jbx/proprietary/
total 70404
-rwxrwxrwx 1 vagrant vagrant 72087592 Jan  7 04:34 jdk-6u45-linux-x64.bin
-rw-r--r-- 1 vagrant vagrant      219 Jan  2 10:32 README.mkd
```
but, the `curl` command still came out the same error. maybe I miss some operation? Could you help me figure out that? Thanks!

**Comment by kalhauge** [comment]
Hi @lmnsyunhao, 

It looks like you are doing the right thing, so I can't quite figure out what is wrong. Here are some options that you could try: 

1. Run the curl command directly and see if it completes: 

```
curl file:///home/vagrant/jbx/proprietary/jdk-6u45-linux-x64.bin
```

2. Alternatively, you might have to preload the file into the system: 

```
nix-prefetch-url file:///home/vagrant/jbx/proprietary/jdk-6u45-linux-x64.bin
```

and then run your jbx command again and see if that works.

3. If none of these approaches works you can also run jbx with a newer version of java which it automatically downloads: 

```
./jbx -J9 analyse -a deadlocks.dirk -o baseline-transfer
```

Let me know if it works :)

**Comment by lmnsyunhao** [comment]
It's work. I used `prefetch` to preload the file. Thanks! But, here comes another problem. 
```
builder for '/nix/store/wcrf6fm9g3y805g30gs85a6v5lxvm7n1-wiretap-tools-0.1.0.0.drv' failed with exit code 1
building '/nix/store/mar9k1yy1y85qglzv2i7zjkh9klvdlax-baseline.drv'...
unpacking sources
unpacking source archive /nix/store/mbxvm42pymlm047rrllyrnfpv6rc8vg8-baseline-52ab27c
source root is baseline-52ab27c
patching sources
building
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/tools/ant/launch/Launcher : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: org.apache.tools.ant.launch.Launcher.  Program will exit.
builder for '/nix/store/mar9k1yy1y85qglzv2i7zjkh9klvdlax-baseline.drv' failed with exit code 1
building '/nix/store/vjyfj7yi4qlb4f6039bl8nw2q5vhhwr3-wiretap.drv'...
unpacking sources
unpacking source archive /nix/store/5ih2yk6kq39c0cg4xi9n4wl0i3ysc0vg-wiretap-33907ef
source root is wiretap-33907ef
patching sources
building
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/tools/ant/launch/Launcher : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: org.apache.tools.ant.launch.Launcher.  Program will exit.
builder for '/nix/store/vjyfj7yi4qlb4f6039bl8nw2q5vhhwr3-wiretap.drv' failed with exit code 1
cannot build derivation '/nix/store/w750abnxcch1l122y2x9dmy54cdlmvr1-wiretap+baseline-transferJ6.default.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/rrhhwi578d56h7c7lbh81w6a3d49p2vl-wiretap-deadlock+baseline-transferJ6.default.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/j064mg1ca8jj72fx5dxa27znq6fzylkd-wiretap-deadlock+baseline-transferJ6.drv': 1 dependencies couldn't be built
error: build of '/nix/store/j064mg1ca8jj72fx5dxa27znq6fzylkd-wiretap-deadlock+baseline-transferJ6.drv' failed
```
Seems the java version or ant version is mismatched. I try to install openjdk from 7 to 10, each version cannot fix this problem. I check the ant version is 1.9.6. Maybe the ant version is old? What should I do? Thanks for helping me.

**Comment by kalhauge** [comment]
Installing java on the system will not help since every build is run in a sandbox. I'll suggest that you try to run the system with java9: 

```
./jbx -J9 analyse -a deadlocks.dirk -o baseline-transfer
```

**Comment by lmnsyunhao** [comment]
Actually, I had already try this command. 
```
[vagrant@nixos:~/jbx]$ ./jbx -J9 analyse -a deadlocks.dirk -o baseline-transfer
usage: jbx [-h] [--filename FILENAME] [--debug] [--dry-run] [--java JAVA]
           [--environment ENVIRONMENT] [--keep-failed] [--short-curcuit]
           [--timeout TIMEOUT]
           {analyse,run,list,tool,add,benchmark,fetch} ...
jbx: error: unrecognized arguments: -J9
```
Then, I tried 
```
[vagrant@nixos:~/jbx]$ ./jbx --java 9 analyse -a deadlocks.dirk -o baseline-transfer
error: attribute 'java9' missing, at /tmp/tmpu4mwvdqj:4:10
(use '--show-trace' to show detailed location information)
2020-01-14 01:49:21,733 jbx.nixutils ERROR    Failed while running nix-build --keep-going /tmp/tmpu4mwvdqj
Failed while running program
```
Then, The log tell me that
```
[vagrant@nixos:~/jbx]$ nix-build --keep-going /tmp/tmpu4mwvdqj --show-trace
error: while evaluating 'splitString' at /home/vagrant/jbx/nixpkgs/lib/strings.nix:299:23, called from /home/vagrant/jbx/expr/utils/default.nix:178:31:
while evaluating 'recurse' at /home/vagrant/jbx/nixpkgs/lib/strings.nix:309:24, called from /home/vagrant/jbx/nixpkgs/lib/strings.nix:320:7:
while evaluating 'addContextFrom' at /home/vagrant/jbx/nixpkgs/lib/strings.nix:286:23, called from /home/vagrant/jbx/nixpkgs/lib/strings.nix:302:11:
while evaluating the attribute 'name' at /home/vagrant/jbx/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:177:11:
while evaluating 'splitString' at /home/vagrant/jbx/nixpkgs/lib/strings.nix:299:23, called from /home/vagrant/jbx/expr/utils/default.nix:246:18:
while evaluating 'recurse' at /home/vagrant/jbx/nixpkgs/lib/strings.nix:309:24, called from /home/vagrant/jbx/nixpkgs/lib/strings.nix:320:7:
while evaluating 'addContextFrom' at /home/vagrant/jbx/nixpkgs/lib/strings.nix:286:23, called from /home/vagrant/jbx/nixpkgs/lib/strings.nix:302:11:
while evaluating the attribute 'name' at /home/vagrant/jbx/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:177:11:
while evaluating the attribute 'name' at /home/vagrant/jbx/expr/utils/default.nix:51:7:
while evaluating the attribute 'java.java9' at /home/vagrant/jbx/expr/default.nix:16:12:
attribute 'java9' missing, at /tmp/tmpu4mwvdqj:4:10
```
I get this project from  `git clone` and didn't checkout the commit id. Emmm, How should I do? Thanks!

**Comment by kalhauge** [comment]
Ah, sorry! I think we have only implemented up to java8 in this branch. Try:

```
./jbx --java 8 analyse -a deadlocks.dirk -o baseline-transfer
```

**Comment by lmnsyunhao** [comment]
Thanks! It moves forward for some steps and throws another error. 
```
these derivations will be built:
  /nix/store/wcrf6fm9g3y805g30gs85a6v5lxvm7n1-wiretap-tools-0.1.0.0.drv
  /nix/store/7k08qsp8qqh5823km0swig6fjv092h1l-wiretap-deadlock+baseline-transferJ8.default.drv
  /nix/store/yykrnlrzwi1vqnyd1cmgi56vpq8i827z-wiretap-deadlock+baseline-transferJ8.drv
building '/nix/store/wcrf6fm9g3y805g30gs85a6v5lxvm7n1-wiretap-tools-0.1.0.0.drv'...
setupCompilerEnvironmentPhase
Build with /nix/store/n5i1zdpmk2b1s3z96649xh8f9kr3g96s-ghc-8.4.3.
ignoring (possibly broken) abi-depends field for packages
ignoring (possibly broken) abi-depends field for packages
unpacking sources
unpacking source archive /nix/store/f57xgg0yxl3jkw70qfgymhps7f78gq7w-wiretap-tools-a13055c
source root is wiretap-tools-a13055c
patching sources
compileBuildDriverPhase
setupCompileFlags: -package-db=/tmp/nix-build-wiretap-tools-0.1.0.0.drv-0/setup-package.conf.d -j1 -threaded
[1 of 1] Compiling Main             ( Setup.hs, /tmp/nix-build-wiretap-tools-0.1.0.0.drv-0/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/n09qdpgkfj3wnjfcr3as4x051726djnb-wiretap-tools-0.1.0.0 --libdir=$prefix/lib/$compiler --libsubdir=$abi/$libname --docdir=/nix/store/892vghrmmlfwhcqk76nw32817dh0x04v-wiretap-tools-0.1.0.0-doc/share/doc/wiretap-tools-0.1.0.0 --with-gcc=gcc --package-db=/tmp/nix-build-wiretap-tools-0.1.0.0.drv-0/package.conf.d --ghc-option=-j1 --disable-split-objs --enable-library-profiling --profiling-detail=exported-functions --disable-profiling --enable-shared --disable-coverage --enable-static --disable-executable-dynamic --disable-tests --enable-library-vanilla --enable-library-for-ghci --ghc-option=-split-sections --extra-lib-dirs=/nix/store/s2n99784krxl91mfw3cnn9ylbb5fjvkx-ncurses-6.1/lib --extra-lib-dirs=/nix/store/rxaclc3vhxbzgfllv7601i85z854h48a-gmp-6.1.2/lib
Using Parsec parser
Configuring wiretap-tools-0.1.0.0...
CallStack (from HasCallStack):
  die', called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:958:20 in Cabal-2.2.0.1:Distribution.Simple.Configure
  configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:462:12 in Cabal-2.2.0.1:Distribution.Simple.Configure
  configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:596:20 in Cabal-2.2.0.1:Distribution.Simple
  confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:67:5 in Cabal-2.2.0.1:Distribution.Simple.UserHooks
  configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:178:19 in Cabal-2.2.0.1:Distribution.Simple
  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:115:27 in Cabal-2.2.0.1:Distribution.Simple
  defaultMain, called at Setup.hs:2:8 in main:Main
Setup: Encountered missing dependencies:
base ==4.9.*

builder for '/nix/store/wcrf6fm9g3y805g30gs85a6v5lxvm7n1-wiretap-tools-0.1.0.0.drv' failed with exit code 1
cannot build derivation '/nix/store/7k08qsp8qqh5823km0swig6fjv092h1l-wiretap-deadlock+baseline-transferJ8.default.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/yykrnlrzwi1vqnyd1cmgi56vpq8i827z-wiretap-deadlock+baseline-transferJ8.drv': 1 dependencies couldn't be built
error: build of '/nix/store/yykrnlrzwi1vqnyd1cmgi56vpq8i827z-wiretap-deadlock+baseline-transferJ8.drv' failed
2020-01-15 03:08:10,888 jbx.nixutils ERROR    Failed while running nix-build --keep-going /tmp/tmpfg8s47cd
Failed while running program
```
Missing `base 4.9.*` ? Is `base` is a `lib`? Maybe I should `nix-env -i`? Thanks!

**Comment by kalhauge** [comment]
Hi, It seems that an upgrade of the dependencies made it impossible to compile wiretap-tools. I have updated the tools and it should work now :). Upgrade to the newest version of master 0bfa10b and the command should run: 

```
$ ./jbx --java 8 analyse -a deadlocks.dirk -o baseline-transfer
...
>>>> JBX-STARTED wiretap-deadlock+baseline-transferJ8.default wiretap-tools-none <<<<
Filters: ["mhb","lockset"]
Human Readable: True
At event 0
Found 1 candidate(s).
 -+    29 | t1.9 request r!2 ++    51 | t2.9 request r!1
- after filter: 1
- distinct: 1
- not proven: 1
Found: "edu/ucla/pls/baseline/Store.add:(I)V!-1 edu/ucla/pls/baseline/Store.add:(I)V!-1"
    -:   29 | t1.9 request r!2
    -:   51 | t2.9 request r!1
Done
>>>> JBX-DONE wiretap-deadlock+baseline-transferJ8.default wiretap-tools-none <<<<
```

**Comment by lmnsyunhao** [comment]
It worked! Thanks! By the way, does the dacapo benchmark can be test using this project now? have the dacapo benchmarks been added in this project now? I saw TODO in the README file. if yes, how to run it? I tried `./jbx --java 8 analyse -a deadlocks.dirk -o dacapo-avrora`, but failed. Thanks!

**Comment by kalhauge** [comment]
Great to hear :). 
To run other benchmarks choose them from the benchmarks list: 

```
./jbx list --benchmarks
```

Not all of them will work though. Running avrora can be done like this: 

```
./jbx --java 8 analyse -a deadlocks.dirk -o avrora
```
